extendsAttributes:

  # 获取数据权限信息
  dataPermissions:
    cache:
      manager: com.gillion.devops.authentication.session.cache.CompositeSessionCache
      compositeKey: Session.get('roleIds')
      expireTimeout: 3600
      level: L2
    service:
      type: Netty
      name: "netty://com.gillion.devops.authentication.centre.api.SessionService:getDataPermissionsByRoleId:1.0"
      returnType: "[Lcom.gillion.devops.authentication.support.ipf.Table;"