###单个插入
GET http://127.0.0.1:8080/ec-demo/insert1

###单个更新
GET http://127.0.0.1:8080/ec-demo/update1

###单个删除
GET http://127.0.0.1:8080/ec-demo/delete1

### 批量插入
GET http://127.0.0.1:8080/ec-demo/insert2

### post请求
POST http://127.0.0.1:8080/ec-demo/query1
Content-Type: application/x-www-form-urlencoded

cname=张三&mobile=123

###
DELETE http://localhost:8080/ec-demo/delete1/22


### get请求
GET http://127.0.0.1:8080/users/roles?username=wengms


### post请求
POST http://127.0.0.1:8080/taskDetailInfo/saveOffer
Content-Type: application/json

{
  "uemUserName": "小陈",
  "applyDate": "2022-08-01",
  "offerType": "www",
  "approver": 10,
  "standardDetailId": 11,
  "standardEntryId": 12
}